# Generated by Django 5.0.6 on 2024-07-05 07:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TablaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('razon_social', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TablaEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TablaProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prov', models.CharField(max_length=100)),
                ('rut_prov', models.CharField(max_length=100, unique=True)),
                ('correo_prov', models.EmailField(max_length=254)),
                ('telefono_prov', models.IntegerField()),
                ('razon_social_prov', models.CharField(max_length=100)),
                ('direccion_prov', models.CharField(max_length=100)),
                ('region_prov', models.CharField(max_length=100)),
                ('comuna_prov', models.CharField(max_length=100)),
                ('ncontacto_prov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_egreso', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablacliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaprov')),
            ],
        ),
        migrations.CreateModel(
            name='TablaVariedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=100, unique=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie', to_field='especie')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenIngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('id_orden_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordeningreso')),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablacalidad')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEgresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('id_orden_egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordenegreso')),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablacalidad')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad')),
            ],
        ),
    ]
