# Generated by Django 5.0.6 on 2024-06-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablaprov',
            name='razon_social_prov',
            field=models.CharField(max_length=100),
        ),
    ]
