# Generated by Django 5.0.6 on 2024-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tablacliente_value_tablacliente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablacliente',
            name='telefono',
            field=models.IntegerField(default=912345678),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablacliente',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
