# Generated by Django 5.0.6 on 2024-06-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablacliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tablaprov',
            name='telefono_prov',
            field=models.IntegerField(),
        ),
    ]
