# Generated by Django 5.0.6 on 2024-06-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tablacliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='rut_prov_ing',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='variedad',
        ),
        migrations.CreateModel(
            name='OrdenIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaprov')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenIngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad')),
                ('id_orden_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordeningreso')),
            ],
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
