# Generated by Django 5.0.6 on 2024-06-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tablacliente_telefono_alter_tablacliente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('correo', models.EmailField(default='default@example.com', max_length=254)),
                ('telefono', models.IntegerField()),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('ncontacto', models.CharField(max_length=100)),
            ],
        ),
    ]
