# Generated by Django 5.0.6 on 2024-06-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tablaprov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablaprov',
            old_name='comuna',
            new_name='comuna_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='correo',
            new_name='correo_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='direccion',
            new_name='direccion_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='name',
            new_name='name_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='ncontacto',
            new_name='ncontacto_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='razon_social',
            new_name='razon_social_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='region',
            new_name='region_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='rut',
            new_name='rut_prov',
        ),
        migrations.RenameField(
            model_name='tablaprov',
            old_name='telefono',
            new_name='telefono_prov',
        ),
    ]
