# Generated by Django 5.0.6 on 2024-06-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ingreso_especie_remove_ingreso_rut_prov_ing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningresodetalle',
            name='fruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_ingreso_detalles', to='core.tablavariedad'),
        ),
        migrations.AlterField(
            model_name='ordeningresodetalle',
            name='id_orden_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ordeningreso'),
        ),
    ]
