# Generated by Django 5.0.6 on 2024-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_comuna_tablaprov_comuna_prov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaFruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('variedad', models.CharField(max_length=100)),
                ('calidad', models.CharField(max_length=100)),
            ],
        ),
    ]
