# Generated by Django 5.0.6 on 2024-06-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ordeningresodetalle_fruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningresodetalle',
            name='fruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad'),
        ),
        migrations.AlterField(
            model_name='ordeningresodetalle',
            name='id_orden_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordeningreso'),
        ),
    ]
