# Generated by Django 5.0.6 on 2024-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tablafruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tablaprov',
            name='id',
        ),
        migrations.AlterField(
            model_name='tablacliente',
            name='rut',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tablaprov',
            name='rut_prov',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
