# Generated by Django 5.0.6 on 2024-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordeningresodetalle_fruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablavariedad',
            name='cantidad_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
