# Generated by Django 5.0.6 on 2024-06-07 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tablacliente_id_remove_tablaprov_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablafruta',
            name='id',
        ),
        migrations.AddField(
            model_name='tablafruta',
            name='codigo',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_fruta_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablafruta')),
                ('rut_prov_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaprov')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_fruta_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablafruta')),
                ('rut_prov_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablacliente')),
            ],
        ),
    ]
