# Generated by Django 5.0.6 on 2024-06-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tablavariedad_cantidad_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordeningresodetalle',
            name='calidad',
        ),
    ]
