# Generated by Django 5.0.6 on 2024-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ordeningresodetalle_calidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningresodetalle',
            name='cantidad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
