# Generated by Django 5.0.6 on 2024-06-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tablafruta_id_tablafruta_codigo_ingreso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablacliente',
            name='razon_social',
            field=models.CharField(default=' - ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tablacliente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tablacliente',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tablaprov',
            name='correo_prov',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tablaprov',
            name='razon_social_prov',
            field=models.CharField(default=' - ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tablaprov',
            name='telefono_prov',
            field=models.IntegerField(unique=True),
        ),
    ]
