# Generated by Django 5.0.6 on 2024-06-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ordeningresodetalle_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablacliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEgresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad')),
                ('id_orden_egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordenegreso')),
            ],
        ),
    ]
