# Generated by Django 5.0.6 on 2024-06-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tablacliente_razon_social_alter_tablacliente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TablaVariedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Orden',
            new_name='Egreso',
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='codigo_fruta_ing',
            new_name='codigo_fruta_egr',
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='order_date',
            new_name='order_date_egr',
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='rut_prov_ing',
            new_name='rut_prov_egr',
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='total_amount',
            new_name='total_amount_egr',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='codigo_fruta_ord',
            new_name='codigo_fruta_ing',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='order_date',
            new_name='order_date_ing',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='rut_prov_ord',
            new_name='rut_prov_ing',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='total_amount',
            new_name='total_amount_ing',
        ),
        migrations.AlterField(
            model_name='tablafruta',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie', to_field='especie'),
        ),
        migrations.AlterField(
            model_name='tablafruta',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad', to_field='variedad'),
        ),
    ]
