# Generated by Django 5.0.6 on 2024-06-30 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ordenegreso_ordenegresodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tablavariedad',
            name='calidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.tablacalidad', to_field='calidad'),
            preserve_default=False,
        ),
    ]
