# Generated by Django 5.0.6 on 2024-06-07 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tablaespecie_tablavariedad_rename_orden_egreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablavariedad',
            name='especie',
            field=models.ForeignKey(default=' - ', on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie', to_field='especie'),
            preserve_default=False,
        ),
    ]
