# Generated by Django 5.0.6 on 2024-06-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tablacalidad_tablavariedad_calidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablacliente',
            name='razon_social',
            field=models.CharField(default='', max_length=100),
        ),
    ]
