# Generated by Django 5.0.6 on 2024-06-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_calidad_tablafruta_calidad_fruta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablaespecie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tablafruta',
            name='especie_fruta',
        ),
        migrations.RemoveField(
            model_name='tablafruta',
            name='variedad_fruta',
        ),
        migrations.RemoveField(
            model_name='tablavariedad',
            name='id',
        ),
        migrations.AlterField(
            model_name='tablaespecie',
            name='especie',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tablavariedad',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie'),
        ),
        migrations.AlterField(
            model_name='tablavariedad',
            name='variedad',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
