# Generated by Django 5.0.6 on 2024-06-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tablafruta_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablafruta',
            name='especie',
            field=models.ForeignKey(default='Especie', on_delete=django.db.models.deletion.CASCADE, related_name='frutas_especie', to='core.tablavariedad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablafruta',
            name='variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frutas_variedad', to='core.tablavariedad'),
        ),
    ]
