# Generated by Django 5.0.6 on 2024-06-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_variedad_tablafruta_variedad_fruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablafruta',
            name='especie_fruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablaespecie'),
        ),
        migrations.AlterField(
            model_name='tablafruta',
            name='variedad_fruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablavariedad'),
        ),
    ]
