# Generated by Django 5.0.6 on 2024-06-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_especie_fruta_tablafruta_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='codigo_fruta_egr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='codigo_fruta_ing',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TablaFruta',
        ),
    ]
