# Generated by Django 5.0.6 on 2024-06-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
